package org.fyp.tmssep490be.dtos.enrollment;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.fyp.tmssep490be.entities.enums.Gender;

import java.time.LocalDate;

/**
 * Data của mỗi student trong Excel (sau khi parse)
 * Simplified 7-column format: full_name, email, phone, facebook_url, address, gender, dob
 *
 * Student code will be auto-generated by the system
 * Assessment data is handled separately through dedicated endpoints for individual student creation
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StudentEnrollmentData {
    // From Excel - Simplified 7 columns
    // private String studentCode;  // REMOVED - auto-generated by system
    private String fullName;      // Required
    private String email;         // Required
    private String phone;         // Required
    private String facebookUrl;   // Optional - important for sales communication
    private String address;       // Optional - important for location-based recommendations
    private Gender gender;        // Required
    private LocalDate dob;        // Required

    // REMOVED: Assessment fields - handled separately through individual student creation workflow
    // private String general, reading, writing, speaking, listening;

    // Resolution result (sau khi system xử lý)
    private StudentResolutionStatus status;  // FOUND/CREATE/DUPLICATE/ERROR
    private Long resolvedStudentId;  // Nếu FOUND
    private String errorMessage;  // Nếu ERROR
}
